[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "worker"
test = false
bench = false
path = "src/worker/main.rs"

[[bin]]
name = "cam"
test = false
bench = false
path = "src/cam/main.rs"

[[bin]]
name = "cv"
test = false
bench = false
path = "src/cv/main.rs"


[[bin]]
name = "orb"
test = false
bench = false
path = "src/orb/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = { path = "lib" }
anyhow = "1.0.79"
deadpool = { version = "0.11.2", features = ["unmanaged"] }
fantoccini = "0.19.3"
futures = "0.3.30"
log = "0.4.20"
queues = "1.1.0"
rayon = "1.8"
async-trait = "0.1.78"
lapin = "2.3.1"
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.4"
bytes = "1.6.0"
diesel = { version = "2.1.6", features = ["sqlite", "numeric"] }
dotenvy = "0.15.7"
tracing = "0.1.40"
itertools = "0.12.1"
tracing-subscriber = "0.3.18"
serde_json = "1.0.116"
opencv = "0.91.3"
